import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import './globals.css'
import Providers from './Providers/Providers'

const ManropeSans = Manrope({
    variable: '--font-manrope-sans',
    subsets: ['latin', 'cyrillic'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${ManropeSans.variable} antialiased`}
                style={{ backgroundColor: '#F5F7FB' }}
            >
                <Providers>{children}</Providers>
            </body>
        </html>
    )
}
